### ISSUE TITLE
SDK7 Each time you try to start a video from a 2D UI, you must also click in the scene

### ISSUE THREAD

**Issue by cfravel** [decentraland/sdk#928]
If you use a click on a 3D entity in a scene to start a video, it works fine.
If you use a 2D UI button to start a video, you must, each time you wish to do so, also click into the scene.
Pause/Stop actions work fine from 2D UIs without having to click in the scene

Exemplified by:
https://gitlab.com/dcl-tech/videodemo

Steps to reproduce:
1. Clone the above scene
2. Run it in preview in browser
3. Click on the green box to start the movie, yellow to pause it, or red to stop it.
4. Click on the play button in the 2D UI
// Expected:  video starts
// Actual: video doesn;t  start until you also click in the scene (away from the 2D UI)
5. 2D Stop and Pause work fine
Note that the 2D and 3D controls work in tandem, you can use either interchangeably in this demo.

**Comment by pbosio** [comment]
@cfravel issue should be fixed on next release

**Comment by cfravel** [comment]
@pbosio 
I've retested in 7.3.15 and not yet fixed, but in release notes for recent releases through 7.3.15 I don't see mention of it yet.
What release will it be in?
Will somebody test it against my demo scene that I linked above to confirm that the change you merged addresses this?

**Comment by pbosio** [comment]
@cfravel we had to release some changes, but this fix was not included.
we are waiting for and explorer version to be released for this changes to be included.
in the mid time you could add `&explorer-branch=dev` to the url where the issue is fixed.
I personally tested your demo scene to make sure the issue was fixed :)

**Comment by cfravel** [comment]
Indeed I find it to work properly in-world using that `&explorer-branch=dev` addition to the URL.
Thank you!

**Comment by cfravel** [comment]
@pbosio @pravusjif 
Please look at these together, and try to work a solution that keeps the long-standing functionality of my 2D-driven movie theaters working
https://github.com/decentraland/sdk/issues/928
https://github.com/decentraland/sdk/issues/986

**Comment by cfravel** [comment]
Please also bump up the priority on this other funtionality-blocker for my movie theaters:
https://github.com/decentraland/unity-renderer/issues/5675

**Comment by cfravel** [comment]
This has been fixed in V2 client.  (still exists in legacy clients)
