### ISSUE TITLE
Modifiers area hide function doesn't respect excludeId for client

### ISSUE THREAD

**Issue by drexample** [decentraland/sdk#999]
### **Steps to reproduce:**

  1. Create a modifier area with modifiers: [AvatarModifierType.AMT_HIDE_AVATARS]
  2. Add IDs to excludeIds
  3. Observe it hide client's avatar both in first and second person modes
### **Expected behaviour:**

For the avatars attached to client's ID in excludeIds to not be affected and still be visible

### **Current behaviour:**

It hides user avatar, disregarding it being included in the list of exceptions

### **Reproduction rate:**

100%, currently live at MRT building (Meta Residence Tower) upon entering the lobby. Does not reproduce locally at all.

### **Severity:**

- [ ] Cosmetic
- [ ] Minor
- [x] Medium
- [ ] High
- [ ] Critical
- [ ] Blocker

### **Priority:**
- [ ] High
- [x] Medium
- [ ] Low

### **Platforms:**
- [ ] Windows
- [ ] Mac
- [x] Not platform specific

### **Browser:**
- [ ] Google Chrome
- [ ] Microsoft Edge
- [ ] Firefox
- [ ] Desktop
- [x] Not Browser Specific

### **Environment:**
- [x] Production
- [ ] Branch specific
- [ ] Release Branch

#### **Additional Notes:**

Tested AFTER the latest SDK rollout.

**Comment by pravusjif** [comment]
I confirm the problem, I just did a little test and that component is still bugged =(

**Comment by pravusjif** [comment]
@drexample can you test on your side again? It should be working fine with production's build right now

**Comment by drexample** [comment]
> @drexample can you test on your side again? It should be working fine with production's build right now

Nope, still broken. Even when leaving the area, the avatar keeps being hidden.

**Comment by yanis7774** [comment]
> @drexample can you test on your side again? It should be working fine with production's build right now

Can confirm. Doesn't work.

**Comment by pravusjif** [comment]
The feature is working fine when used normally:
You can test that yourself by following the test instructions in [that feature's latest fix PR description](https://github.com/decentraland/unity-renderer/pull/5791) but using production's build instead, with [this playground link](https://playground.decentraland.org/?code=Y29uc3QgZXhjbHVkZWRVc2VyID0gJ1VTRVItV0FMTEVULUFERFJFU1MtR09FUy1IRVJFJwpjb25zdCBhdmF0YXJNb2RpZmllckFyZWFFbnRpdHkgPSBlbmdpbmUuYWRkRW50aXR5KCkKY29uc3QgYXJlYVNpemUgPSBWZWN0b3IzLmNyZWF0ZSg0LCA0LCA0KQoKVHJhbnNmb3JtLmNyZWF0ZShhdmF0YXJNb2RpZmllckFyZWFFbnRpdHksIHsgCiAgcG9zaXRpb246IFZlY3RvcjMuY3JlYXRlKDgsIDEsIDgpLAogIHNjYWxlOiBhcmVhU2l6ZQp9KQpBdmF0YXJNb2RpZmllckFyZWEuY3JlYXRlKGF2YXRhck1vZGlmaWVyQXJlYUVudGl0eSwgewogIGFyZWE6IGFyZWFTaXplLAogIG1vZGlmaWVyczogW0F2YXRhck1vZGlmaWVyVHlwZS5BTVRfSElERV9BVkFUQVJTXSwKICBleGNsdWRlSWRzOiBbZXhjbHVkZWRVc2VyXQp9KQpNZXNoUmVuZGVyZXIuc2V0Qm94KGF2YXRhck1vZGlmaWVyQXJlYUVudGl0eSkKTWF0ZXJpYWwuc2V0UGJyTWF0ZXJpYWwoYXZhdGFyTW9kaWZpZXJBcmVhRW50aXR5LCB7IGFsYmVkb0NvbG9yOiBDb2xvcjQuY3JlYXRlKDAuNSwgMC41LCAwLjUsIDAuNSkgfSkKCgo%3D&explorer-branch=main).

If you correctly enter in a second window using `?ENABLE_WEB3`, the client will be able to actually read the wallet address to be able to exclude it (in production, AKA a deployed land, that url param is not needed as that is enabled by default, but not in preview/local mode).

@drexample @yanis7774 if you confirm on your side that those test instructions work fine as they do in my case, you can maybe figure out what you are doing differently in your code, otherwise you can share a code snippet of your implementation here.

**Comment by yanis7774** [comment]
> The feature is working fine when used normally: You can test that yourself by following the test instructions in [that feature's latest fix PR description](https://github.com/decentraland/unity-renderer/pull/5791) but using production's build instead, with [this playground link](https://playground.decentraland.org/?code=Y29uc3QgZXhjbHVkZWRVc2VyID0gJ1VTRVItV0FMTEVULUFERFJFU1MtR09FUy1IRVJFJwpjb25zdCBhdmF0YXJNb2RpZmllckFyZWFFbnRpdHkgPSBlbmdpbmUuYWRkRW50aXR5KCkKY29uc3QgYXJlYVNpemUgPSBWZWN0b3IzLmNyZWF0ZSg0LCA0LCA0KQoKVHJhbnNmb3JtLmNyZWF0ZShhdmF0YXJNb2RpZmllckFyZWFFbnRpdHksIHsgCiAgcG9zaXRpb246IFZlY3RvcjMuY3JlYXRlKDgsIDEsIDgpLAogIHNjYWxlOiBhcmVhU2l6ZQp9KQpBdmF0YXJNb2RpZmllckFyZWEuY3JlYXRlKGF2YXRhck1vZGlmaWVyQXJlYUVudGl0eSwgewogIGFyZWE6IGFyZWFTaXplLAogIG1vZGlmaWVyczogW0F2YXRhck1vZGlmaWVyVHlwZS5BTVRfSElERV9BVkFUQVJTXSwKICBleGNsdWRlSWRzOiBbZXhjbHVkZWRVc2VyXQp9KQpNZXNoUmVuZGVyZXIuc2V0Qm94KGF2YXRhck1vZGlmaWVyQXJlYUVudGl0eSkKTWF0ZXJpYWwuc2V0UGJyTWF0ZXJpYWwoYXZhdGFyTW9kaWZpZXJBcmVhRW50aXR5LCB7IGFsYmVkb0NvbG9yOiBDb2xvcjQuY3JlYXRlKDAuNSwgMC41LCAwLjUsIDAuNSkgfSkKCgo%3D&explorer-branch=main).
> 
> If you correctly enter in a second window using `?ENABLE_WEB3`, the client will be able to actually read the wallet address to be able to exclude it (in production, AKA a deployed land, that url param is not needed as that is enabled by default, but not in preview/local mode).
> 
> @drexample @yanis7774 if you confirm on your side that those test instructions work fine as they do in my case, you can maybe figure out what you are doing differently in your code, otherwise you can share a code snippet of your implementation here.

Hi @pravusjif,

The bug is still there. I will attach a video illustrating the bug. 
In the video, I demonstrate how we exclude avatars by printing the excluded addresses in a console. 

Moreover, when I leave the scene, it continues to behave in this manner.


Uploading hidden_avatars_bug_resized.mov…

**Comment by yanis7774** [comment]
https://github.com/decentraland/sdk/assets/34626980/f746c19d-4dc7-4944-9bc7-184779209689

**Comment by pravusjif** [comment]
Uhmm, based on what you show you may be dealing with 2 bugs:
1. Dynamically changing the excluded ids for the AvatarModifierArea (as you do, using the mutable instance) appears to be bugged
2. When you leave the a scene whose avatar modifier area occupies entirely, your avatar is not being reset.

I took a quick look on our implementation and both cases should be covered but since they appear to be bugged I'll take a deeper look to debug

**Comment by yanis7774** [comment]
> Uhmm, based on what you show you may be dealing with 2 bugs:
> 
> 1. Dynamically changing the excluded ids for the AvatarModifierArea (as you do, using the mutable instance) appears to be bugged
> 2. When you leave the a scene whose avatar modifier area occupies entirely, your avatar is not being reset.
> 
> I took a quick look on our implementation and both cases should be covered but since they appear to be bugged I'll take a deeper look to debug

Thank you for the update. We have conducted tests with both dynamic and static configurations for the AvatarModifierArea. In both scenarios, the issue persisted, indicating that the problem might not solely lie with the dynamic changes.

**Comment by pravusjif** [comment]
I've been able to reproduce the issue consistently: it happens when the user id is added to the avatar modifier area excluded ids collection AFTER the user is already inside the area...

I'll try to find a solution.

**Comment by pravusjif** [comment]
Fixed at https://github.com/decentraland/unity-renderer/pull/6038

Will reach production with next explorer release + subsequent SDK release

**Comment by pravusjif** [comment]
Fix released with [@dcl/sdk@7.3.36](https://github.com/decentraland/js-sdk-toolchain/releases/tag/7.3.36)

**Comment by pravusjif** [comment]
Tried to replicate the problem reported at Meta Residence Tower but I still can't...

Here I tried with 3 different users, 2 of them are in the excluded ids list that I empty/re-fill toggling it with that cube:

https://github.com/decentraland/sdk/assets/1031741/d0e2624b-7207-4516-980e-c06f8d00a19a

```
const excludedUser1 = 'USER-ID/WALLET-ADDRESS-1'
const excludedUser2 = 'USER-ID/WALLET-ADDRESS-2'
const avatarModifierAreaEntity = engine.addEntity()
const areaSize = Vector3.create(4, 4, 4)
Transform.create(avatarModifierAreaEntity, { 
position: Vector3.create(8, 1, 8),
scale: areaSize
})
AvatarModifierArea.create(avatarModifierAreaEntity, {
area: areaSize,
modifiers: [AvatarModifierType.AMT_HIDE_AVATARS],
excludeIds: []
})
MeshRenderer.setBox(avatarModifierAreaEntity)
Material.setPbrMaterial(avatarModifierAreaEntity, { albedoColor: Color4.create(0.5, 0.5, 0.5, 0.5) })
const cube = createCube(8, 1, 12, false)
MeshCollider.setBox(cube)
pointerEventsSystem.onPointerDown(
  { entity: cube, opts: { button: InputAction.IA_POINTER, hoverText: 'toggle excluded id' } },
  () => {
    const mutable = AvatarModifierArea.getMutable(avatarModifierAreaEntity)
    if (mutable.excludeIds.includes(excludedUser1) && mutable.excludeIds.includes(excludedUser2)) {
      mutable.excludeIds = []
      console.log(`REMOVED excluded users`)
    }
    else {
      mutable.excludeIds = [excludedUser1, excludedUser2]
      console.log(`ADDED excluded users`)
    }
  }
)

function createCube(x: number, y: number, z: number, spawner = true): Entity {
  const entity = engine.addEntity()
  Transform.create(entity, { position: { x, y, z } })
  MeshRenderer.setBox(entity)
  MeshCollider.setBox(entity)
  Material.setPbrMaterial(entity, { albedoColor: Color4.Red() })
  return entity
}
```

@drexample @yanis7774 can you provide us with an isolated snippet in which you can reproduce the problem?

Otherwise in Meta Tower you could do something like rendering a semi-transparent cube (as I do in the snippet I provided above) to make sure the area is in the correct place with the correct size
